### PR TITLE
-coverprofile option should be specified before package name

### LINKED ISSUE #69: flag provided but not defined: -coverprofile
Just run `gocov test` but got this.

I'm on go1.5.1.

Seems to be many projets are failing on tests using gocov.

### PR DESCRIPTION
**Pull request by mattn**
Close #69

### CODE REVIEW

**Comment by axw** [comment]
Thanks.

**Comment by jadengore** [comment]
It seems that after this merge, I'm now getting this error when I run `gocov`:

`flag provided but not defined: -test.coverprofile`.

Could it result from this change and any suggestions on how to proceed to update my code?

**Comment by mattn** [comment]
arguments should be ordered with `gocov` `flags` `packages`.

**Comment by jadengore** [comment]
@mattn I'm using Go's `flag` package to load a config file, and I'm running into an issue. Here's the output:

```
gocov test -v -config=test ./...                                                Sun Nov  8 18:49:40 2015
?   	github.com/jadengore/package-name	[no test files]
{"Packages":null}
```

**Comment by mattn** [comment]
What package did you try?

**Comment by jbrodriguez** [comment]
I'm having the same problem:

`flag provided but not defined: -test.coverprofile`

My 'main.go' and 'main_test.go' scan env variables with code from github.com/namsral/flag, which is mostly very similar to the built-in flag package

I tried defining the variable, but I got a more cryptic error 

`invalid boolean value "/var/folders/nt/pwdf3rm96w18228g3xx4fsnh0000gn/T/gocov488181658/test0.cov" for  -test.coverprofile: strconv.ParseBool: parsing "/var/folders/nt/pwdf3rm96w18228g3xx4fsnh0000gn/T/gocov488181658/test0.cov": invalid syntax`

**Comment by jbrodriguez** [comment]
I redefined test.coverprofile as a flag.StringVar rather than a flag.BoolVar, and it passed.

I had to add test.outputdir as a flag.StringVar to make it finally work.

**Comment by mattn** [comment]
@jadengore thank your figure out the issue.

**Comment by jadengore** [comment]
@jbrodriguez Can you give me an example of what it would look like in Go code to redefine `test.coverprofile` in my source?

**Comment by jbrodriguez** [comment]
@jadengore sure. You need to do something similar to this:

```
import (
   "flag"
)

func main() {
   ...
   var testprof, outputdir string

   flag.StringVar(&testprof, "test.coverprofile", "cov.out", "test coverprofile")
   flag.StringVar(&outputdir, "test.outputdir", ".", "test coverprofile")

   flag.Parse()
   ...
}
```
I got test.coverprofile and test.outputdir from the error message.

**Pull request merged**
