### PR TITLE
Support Go 1.18 methods with type parameters

### PR DESCRIPTION
**Pull request by jdemeyer**
Support methods with syntax like
```
func (x *Foo[T]) GenericMethod() {}
```

### CODE REVIEW

**Comment by nezorflame** [comment]
@axw hi! Any chance this could be merged?

**Comment by axw** [comment]
Thanks for the update, LGTM. Sorry for the very slow response - my notifications seem to have gone awry again.

**Comment by nezorflame** [comment]
@axw thanks! Can you also mark a new release with this? Would be nice to have a tag :)

**Comment by axw** [comment]
I should have done that before - done. Thanks for the ping @nezorflame.

**Pull request merged**
