### PR TITLE
Add note about Codecov integration

### PR DESCRIPTION
**Pull request by stevepeak**
> Waiting on https://github.com/AlekSi/gocov-xml/pull/6

Will adjust the `Learn more` to link to the changes proposed above. Thank you!

### CODE REVIEW

**Comment by axw** [comment]
@stevepeak Happy to add a link once the gocov-xml change is made.

It might be worth changing the section title to "Related tools/services", and having Codecov on its own line underneath gocov-xml, with mention of gocov-xml as a requirement. Please keep it as a simple link and brief description, and drop the "Learn More". Interested parties can click through the link to do that.

**Comment by stevepeak** [comment]
How does this look? Thank you @axw  :+1:

**Comment by axw** [comment]
@stevepeak Looks fine, thanks. Please ping when gocov-xml is ready.

**Comment by stevepeak** [comment]
We are all set. Cobertura has been an acceptable format since birth :) Thank you!

**Pull request merged**
