### PR TITLE
codecov support native go coverage report.

### PR DESCRIPTION
**Pull request by appleboy**
See the job: https://travis-ci.org/go-gas/gas/jobs/144392194

### CODE REVIEW

**Comment by axw** [comment]
@stevepeak Since codecov supports Go's native coverage output, it does seem that there's no point in suggesting people to use gocov. Any reason to keep this?

**Comment by stevepeak** [comment]
@axw I'm not a Go expert and only have worked with the gocov package. Would you like to create a pull request with your suggestions on what to change here: https://github.com/codecov/example-go Thanks!

**Comment by appleboy** [comment]
@stevepeak I created new PR yesterday to improve golang test on codecov. I will update `example-go` script and send notification to you if done.

https://github.com/codecov/example-go/pull/6

**Comment by appleboy** [comment]
@axw @stevepeak Done!  Please review PR and detail job information.

https://travis-ci.org/codecov/example-go/builds/144733284
https://github.com/codecov/example-go/pull/6

**Pull request merged**
